fname = input("Enter your First Name: ")
lname = input("Enter your Last Name: ")
mname = input("Enter your Middle Name: ")
bday = input("Enter your Birthday: ")
gen = input("Enter your Gender: ")
addr = input("Enter your Address: ")
crs = input("Enter your Course: ")
yrl = input("Enter your Year Level: ")

print("\n----------------------------------------------\n")
print("Your Name is:", fname, mname, lname)
print("Your Birthday is on:", bday)
print("Your Gender is:", gen)
print("Your Address is:", addr)
print("Your Course is:", crs)
print("Your Year Level is :", yrl)
print("\n----------------------------------------------")